/*
RingEvent.java class

This class represents the events that are generated by the ring.

@author: Mohamed Hassan
@date: 2026-02-24
*/
package main.model;

public class RingEvent {
    //enum for the type of event
    public enum Type{
        ADD_NODE,
        REMOVE_NODE,
        ASSIGN_KEY,
        MIGRATE_KEY
    }

    //instance variables
    private Type type;
    private String message;
    private Object object;
    
    //constructor
    public RingEvent(Type type, String message, Object object){
        this.type = type;
        this.message = message;
        this.object = object;
    }

    //Getters
    public Type getType(){
        return type;
    }
    public String getMessage(){
        return message;
    }
    public Object getObject(){
        return object;
    }
    //toString method
    @Override
    public String toString(){
        return "Ring Event: type = " + type + ", message = " + message + ", object = " + object + ".";
    }

}
